<Project Sdk="Godot.NET.Sdk/4.6.0">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <RootNamespace>VictorianAnimalGame</RootNamespace>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="YamlDotNet" Version="16.3.0" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="Data\Goods\Fish.yaml" />
    <Content Include="Data\Goods\Radio.yaml" />
    <Content Include="Data\Goods\Wood.yaml" />
    <Content Include="Data\Map\Provinces\1-Isle de Tranga.yaml" />
    <Content Include="Data\Map\Provinces\11-New Territory.yaml" />
    <Content Include="Data\Map\Provinces\12-Jessak.yaml" />
    <Content Include="Data\Map\Provinces\13-Readernes.yaml" />
    <Content Include="Data\Map\Provinces\14-Mardes.yaml" />
    <Content Include="Data\Map\Provinces\15-Ligas.yaml" />
    <Content Include="Data\Map\Provinces\16-Voth.yaml" />
    <Content Include="Data\Map\Provinces\17-Pollis.yaml" />
    <Content Include="Data\Map\Provinces\18-Klyde.yaml" />
    <Content Include="Data\Map\Provinces\19-Qale.yaml" />
    <Content Include="Data\Map\Provinces\2-Mengits Inlet.yaml" />
    <Content Include="Data\Map\Provinces\20-Eastern Reach.yaml" />
    <Content Include="Data\Map\Provinces\200-Big Blue Ocean.yaml" />
    <Content Include="Data\Map\Provinces\201-Otter Bay.yaml" />
    <Content Include="Data\Map\Provinces\202-Otter Coast.yaml" />
    <Content Include="Data\Map\Provinces\203-Beaver Sea.yaml" />
    <Content Include="Data\Map\Provinces\21-Skald.yaml" />
    <Content Include="Data\Map\Provinces\22-Fjold.yaml" />
    <Content Include="Data\Map\Provinces\24-Thalgards Pass.yaml" />
    <Content Include="Data\Map\Provinces\23-Trjord.yaml" />
    <Content Include="Data\Map\Provinces\25-Clymthu.yaml" />
    <Content Include="Data\Map\Provinces\26-Thum.yaml" />
    <Content Include="Data\Map\Provinces\27-Abthu.yaml" />
    <Content Include="Data\Map\Provinces\28-Bulthu.yaml" />
    <Content Include="Data\Map\Provinces\29-Yomclu.yaml" />
    <Content Include="Data\Map\Provinces\3-Calm Coast.yaml" />
    <Content Include="Data\Map\Provinces\30-Farbridge.yaml" />
    <Content Include="Data\Map\Provinces\300-Bossa Lake.yaml" />
    <Content Include="Data\Map\Provinces\301-Tandaki Highlands.yaml" />
    <Content Include="Data\Map\Provinces\302-Eastern Expanse.yaml" />
    <Content Include="Data\Map\Provinces\303-Southern Range.yaml" />
    <Content Include="Data\Map\Provinces\31-Sodden Hills.yaml" />
    <Content Include="Data\Map\Provinces\32-Worshire.yaml" />
    <Content Include="Data\Map\Provinces\33-Pludingham.yaml" />
    <Content Include="Data\Map\Provinces\34-Thurrows.yaml" />
    <Content Include="Data\Map\Provinces\35-Dellow.yaml" />
    <Content Include="Data\Map\Provinces\36-Frump.yaml" />
    <Content Include="Data\Map\Provinces\37-Heath.yaml" />
    <Content Include="Data\Map\Provinces\38-Lork.yaml" />
    <Content Include="Data\Map\Provinces\39-Tyre-upon-Avon.yaml" />
    <Content Include="Data\Map\Provinces\4-Jeska.yaml" />
    <Content Include="Data\Map\Provinces\40-Fushi.yaml" />
    <Content Include="Data\Map\Provinces\41-Yamto.yaml" />
    <Content Include="Data\Map\Provinces\42-Tyko.yaml" />
    <Content Include="Data\Map\Provinces\44-Shakiti.yaml" />
    <Content Include="Data\Map\Provinces\43-Shumi.yaml" />
    <Content Include="Data\Map\Provinces\45-Xu.yaml" />
    <Content Include="Data\Map\Provinces\46-Gante.yaml" />
    <Content Include="Data\Map\Provinces\47-Lashi.yaml" />
    <Content Include="Data\Map\Provinces\48-Manatushi.yaml" />
    <Content Include="Data\Map\Provinces\49-Shuni.yaml" />
    <Content Include="Data\Map\Provinces\5-Thumbro.yaml" />
    <Content Include="Data\Map\Provinces\50-Bonji.yaml" />
    <Content Include="Data\Map\Provinces\51-Mannok.yaml" />
    <Content Include="Data\Map\Provinces\52-Swee.yaml" />
    <Content Include="Data\Map\Provinces\53-Dronji.yaml" />
    <Content Include="Data\Map\Provinces\54-Heli.yaml" />
    <Content Include="Data\Map\Provinces\6-Lancers Inlet.yaml" />
    <Content Include="Data\Map\Provinces\7-Sierra.yaml" />
    <Content Include="Data\Map\Provinces\8-The Cut.yaml" />
    <Content Include="Data\Map\Provinces\10-Eastern March.yaml" />
    <Content Include="Data\Map\Provinces\9-Western March.yaml" />
    <Content Include="Data\Map\Views\provinces.bmp" />
    <Content Include="Data\Species\Beaver.yaml" />
    <Content Include="Data\Species\Otter.yaml" />
    <Content Include="Data\Species\Raccoon.yaml" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Engine\Components\Markets\Canton\" />
    <Folder Include="Engine\Time\Processing\" />
  </ItemGroup>
</Project>